# Generated by Django 4.2.7 on 2025-09-03 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='텔레그램 메시지가 전송된 시점', verbose_name='거래 시점')),
                ('asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT', 'Tether'), ('DOGE', 'Dogecoin')], help_text='거래 대상 암호화폐', max_length=10, verbose_name='자산명')),
                ('action', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='매수 또는 매도', max_length=4, verbose_name='거래 행동')),
                ('price', models.DecimalField(decimal_places=2, help_text='KRW 기준 거래 가격', max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='거래 가격')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='매수/매도 비율 (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='거래 비율')),
                ('base_currency', models.CharField(default='KRW', help_text='거래 가격의 기준 통화', max_length=3, verbose_name='기준 통화')),
                ('raw_message', models.TextField(blank=True, help_text='파싱 전 원본 텔레그램 메시지', verbose_name='원본 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '거래',
                'verbose_name_plural': '거래 목록',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='trades_trad_timesta_9d7ed0_idx'), models.Index(fields=['asset'], name='trades_trad_asset_16fcff_idx'), models.Index(fields=['action'], name='trades_trad_action_ced24c_idx'), models.Index(fields=['timestamp', 'asset'], name='trades_trad_timesta_6627ce_idx')],
            },
        ),
    ]
