# Generated by Django 4.2.7 on 2025-09-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT', 'Tether'), ('DOGE', 'Dogecoin'), ('USDC', 'USD Coin')], max_length=10, verbose_name='자산명')),
                ('timestamp', models.DateTimeField(help_text='가격이 기록된 시점', verbose_name='시점')),
                ('price', models.DecimalField(decimal_places=2, help_text='해당 시점의 자산 가격', max_digits=15, verbose_name='가격 (KRW)')),
                ('price_change', models.DecimalField(decimal_places=2, default=0, help_text='이전 가격 대비 변동량', max_digits=10, verbose_name='가격 변동 (KRW)')),
                ('price_change_percentage', models.DecimalField(decimal_places=4, default=0, help_text='이전 가격 대비 변동률', max_digits=8, verbose_name='가격 변동률 (%)')),
                ('volume_indicator', models.DecimalField(decimal_places=2, default=0, help_text='해당 시점의 거래 비율 (추정)', max_digits=5, verbose_name='거래량 지표')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_trade', models.ForeignKey(help_text='이 가격 데이터를 생성한 거래', on_delete=django.db.models.deletion.CASCADE, to='trades.trade', verbose_name='소스 거래')),
            ],
            options={
                'verbose_name': '가격 이력',
                'verbose_name_plural': '가격 이력 목록',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', 'timestamp'], name='trades_pric_asset_48701b_idx'), models.Index(fields=['timestamp'], name='trades_pric_timesta_dcc69e_idx')],
                'unique_together': {('asset', 'timestamp', 'source_trade')},
            },
        ),
    ]
