# Generated by Django 4.2.7 on 2025-09-03 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='BTC_Only, BTC_USDT 등', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('assets', models.JSONField(default=list, help_text="['BTC', 'USDT']")),
                ('initial_budget', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pnl_absolute', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pnl_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('holdings', models.JSONField(default=dict, help_text="{'BTC': 0.1, 'USDT': 1000}")),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('portfolio_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pnl_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('holdings', models.JSONField(default=dict)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('trade_triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.trade')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='portfolios__timesta_fe1331_idx'), models.Index(fields=['portfolio'], name='portfolios__portfol_8cf239_idx')],
            },
        ),
    ]
