# Generated by Django 4.2.7 on 2025-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='current_value',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pnl_absolute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='pnl_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
