# Generated by Django 4.2.7 on 2025-09-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_alter_portfolio_cash_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolios.portfolio'),
        ),
    ]
